### ISSUE TITLE
Compact format outputs redundant information

### ISSUE THREAD

**Issue by boblehest** [slog-rs/term#1]
The output from the compact-format example doesn't match the sample output presented in [slog-rs/slog/README.md#terminal-output-example](https://github.com/slog-rs/slog/blob/358bd063ce37b2ba6eddc5c444cecb34be434597/README.md#terminal-output-example).

Expected output:
```
version: 0.5
  host: localhost, port: 8080
    Oct 27 17:15:20.817 INFO starting
    Oct 27 17:15:20.817 INFO listening
    peer_addr: 82.9.9.9, port: 42381
      Oct 27 17:15:20.817 DEBG connected
      Oct 27 17:15:20.818 DEBG message received, length: 2
    peer_addr: 8.8.8.8, port: 18230
      Oct 27 17:15:20.818 DEBG connected
    peer_addr: 82.9.9.9, port: 42381
      Oct 27 17:15:20.818 DEBG response sent, length: 8
      Oct 27 17:15:20.818 DEBG disconnected
    peer_addr: 8.8.8.8, port: 18230
      Oct 27 17:15:20.818 DEBG message received, length: 2
      Oct 27 17:15:20.818 DEBG response sent, length: 8
      Oct 27 17:15:20.818 DEBG disconnected
    Oct 27 17:15:20.818 INFO exit
```

Actual output:
```
version: 0.5
  host: localhost, port: 8080
    Oct 27 17:15:20.817 INFO starting
    Oct 27 17:15:20.817 INFO listening
  host: localhost, port: 8080
    peer_addr: 82.9.9.9, port: 42381
      Oct 27 17:15:20.817 DEBG connected
      Oct 27 17:15:20.818 DEBG message received, length: 2
  host: localhost, port: 8080
    peer_addr: 8.8.8.8, port: 18230
      Oct 27 17:15:20.818 DEBG connected
  host: localhost, port: 8080
    peer_addr: 82.9.9.9, port: 42381
      Oct 27 17:15:20.818 DEBG response sent, length: 8
      Oct 27 17:15:20.818 DEBG disconnected
  host: localhost, port: 8080
    peer_addr: 8.8.8.8, port: 18230
      Oct 27 17:15:20.818 DEBG message received, length: 2
      Oct 27 17:15:20.818 DEBG response sent, length: 8
      Oct 27 17:15:20.818 DEBG disconnected
  host: localhost, port: 8080
    Oct 27 17:15:20.818 INFO exit
```

Notice how the host and port information is being unnecessarily repeated.

**Comment by dpc** [comment]
Problem introduced here: https://github.com/slog-rs/slog/commit/f7320477d70f3d5a7809fcad2d176af6b24c7eaa#diff-5fd6c9db4afa9990435d35bcf099c320L161

I have a working fix, but it requires casting from trait object to a `const*` which requires unstable features and thus nightly rustc.

I need more time to figure out something that would work on stable. :(

**Comment by dpc** [comment]
The fix requiring nightly: 

```
diff --git a/lib.rs b/lib.rs
index f51a9f4..1cb388e 100644
--- a/lib.rs
+++ b/lib.rs
@@ -12,6 +12,7 @@
 //! }
 //! ```
 #![warn(missing_docs)]
+#![feature(raw)]

 #[macro_use]
 extern crate slog;
@@ -19,7 +20,7 @@ extern crate slog_stream;
 extern crate isatty;
 extern crate chrono;

-use std::{io, fmt, sync};
+use std::{io, fmt, sync, raw, mem};

 use isatty::{stderr_isatty, stdout_isatty};

@@ -158,7 +159,8 @@ impl<D: Decorator> Format<D> {
         };

         if let Some(logger_values) = logger_values_ref.values() {
-            if self.should_print(logger_values_ref as *const _ as usize, indent) {
+            let raw_logger_values: raw::TraitObject = unsafe { mem::transmute(logger_values) };
+            if self.should_print(raw_logger_values.data as *const _ as usize, indent) {
                 try!(self.print_indent(&mut ser.io, indent));
                 let mut clean = true;
                 let mut logger_values = logger_values;
```

**Comment by boblehest** [comment]
Yeah, I assumed that was a no-go. :p Another fix is to expose the `inner` member of `OwnedKeyValueList` and do
```if self.should_print(&*logger_values_ref.inner as *const _ as usize, indent) {```

But you might not want to make that variable public.

**Comment by dpc** [comment]
I like that idea. How about making it `fn id(&self) -> usize` and it would be guaranteed to be unique id identifying given `OwnedKeyValueList`? I think it's an useful thing to have (since term is already relying on it), and the details (pointer casting should be kept inside slog).

If you have time and want to try it out, please do. :)

**Comment by boblehest** [comment]
Yeah, I'll have a look. Guess I'll submit a PR for each repo, and I assume you'll want to take of the versioning.

**Comment by boblehest** [comment]
Actually, I suppose I'll have to wait for a new release of slog with OwnedKeyValueList::id before I update slog-term to use it. :blush:

**Comment by dpc** [comment]
Fixed and published. Thanks again for pointing it out!
