### ISSUE TITLE
slog-term strips colors on msys shell, and emits control characters on windows cmd

### ISSUE THREAD

**Issue by kdy1997** [slog-rs/term#3]
When I call it from windows cmd
```
Nov 26 18:36:15.827[32m INFO [39m[1mtest[0m, [1mscope[0m: 1, [1mversion[0m: 0.5, [1mtest[0m: true
```

When I call it from msys2_shell.bat -mingw64
```
Nov 26 18:37:01.084 INFO test, scope: 1, version: 0.5, test: true
```

It should be at least opposite.

**Comment by kdy1997** [comment]
I assume it's because ```isatty``` on windows version returns true for windows console and false for msys shell.

**Comment by dpc** [comment]
Please check #2

**Comment by kdy1997** [comment]
As https://github.com/dtolnay/isatty/pull/3 is merged and released, it works on msys shell. Emiting control characters on windows is shell is problematic yet, but #2 seems more suitable for it.
