### ISSUE TITLE
1.3.4 with `?` operator breaks semver

### ISSUE THREAD

**Issue by nastevens** [slog-rs/term#6]
In my opinion, using a feature not available prior to the current stable version of Rust breaks backwards compatibility, and therefore breaks semantic versioning. The code in question is the addition of the `?` operator in add5181e67, which was made stable in Rust 1.13. Since we're using Rust in production, we're currently on 1.12 and probably will be for at least a couple more months.

I understand that supporting every stable version of Rust back to 1.0 is not feasible or desirable. But when it's possible, I think it would be best if new syntax features received a new major release (or at least a new minor release).

Would you be okay with a PR that replaces the `?`'s with `try!`s again?

**Comment by dpc** [comment]
TODO: https://www.reddit.com/r/rust/comments/5ntmwk/semantic_versioning_vs_new_language_features/dce8eqs/

**Comment by dpc** [comment]
I have adopted the `clap` policy. I've added in the `slog` README a notice that two versions back will be supported. I've added travis check in main slog repo, slog-term and slog-misc. Slog misc check should protect all the core slog crates.

So I consider it taken care of.
